#!/usr/bin/env bash
# AWS Instance Provisioning Toolkit

# Required for relative references to config files
app=`python3 -c "import os; print(os.path.dirname(os.path.realpath(\"$0\")))"`

# Name/version
name="Docker Provisioner for EC2 instances"
version=`cat ${app}/var/version`

# Core settings
eval venv="~/.provisioner/venv"
eval log="~/.provisioner/log"

# Runs the main app
source "${app}/src/cli.sh"
cli_parse "$@"
