---
- name: Remove old Docker packages
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Install pre-requisites for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Check if Docker GPG keyring already exists
  ansible.builtin.stat:
    path: /usr/share/keyrings/docker-archive-keyring.gpg
  register: docker_gpg_keyring

- name: Add Docker GPG key to keyring if it doesn't exist
  ansible.builtin.shell:
    cmd: >
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
      gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  when: not docker_gpg_keyring.stat.exists

# Docker repository release file doesn't have aarch64 architecture, so remap it to arm64 for compatibility
# Not needed for x86_64 or amd64
- name: Define Docker repository architecture
  set_fact:
    docker_repo_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"

- name: Set up the stable repository
  apt_repository:
    repo: "deb [arch={{ docker_repo_arch }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker-ce-stable

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose
    state: latest
    update_cache: yes

- name: Add user to Docker group
  ansible.builtin.shell:
    cmd: "usermod -aG docker {{ ansible_user }}"

- name: Reset ssh connection to allow user group changes to affect ansible user and restart docker
  ansible.builtin.meta:
    reset_connection
  notify: Restart Docker