plugin: amazon.aws.aws_ec2
regions:
  - ap-southeast-2
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: tag
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address
