---
- name: Ensure bashrc includes necessary environment setup
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: "{{ item }}"
    create: yes
    state: present
  loop:
    - 'export PATH=${PATH}:${HOME}/openbet-stack'
    - 'export STACK_PROJECT_DIR=${HOME}/stack-configuration'
    - 'source ${HOME}/openbet-stack/functions'
  become: yes
  become_user: "{{ ansible_user }}"
  become_method: su
  become_flags: '--login'