---
- name: Running Openbet-stack setup tasks
  block:
  - name: Clone Openbet-stack repository
    git:
      repo: '{{ openbet_stack_repo_url}}'
      dest: "{{ openbet_stack_repo_dest }}"
      version: "{{ openbet_stack_repo_branch }}"

  - name: Create directory for Stack configuration
    file:
      path: "/home/{{ ansible_user }}/stack-configuration"
      state: directory

  become: yes
  become_user: "{{ ansible_user }}"
  become_method: su
  become_flags: '--login'