---
- name: Install and configure Maven
  include_tasks: setup_mvn.yml

- name: Ensure the workspace directory is present
  ansible.builtin.file:
    path: "{{ release_base_dir }}"
    state: directory

- name: Check if workspace directory is empty
  ansible.builtin.find:
    paths: "{{ release_base_dir }}"
    file_type: any
  register: files_in_directory

- name: Initialise or update each application
  include_tasks: setup_app.yml
  loop: "{{ applications }}"
  loop_control:
    loop_var: app