---
- name: Set up Docker on Ubuntu
  include_tasks: os_family/Ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Set up Docker on Amazon Linux 2
  include_tasks: os_family/Amazon.yml
  when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
