---
release_base_dir: "/home/{{ ansible_user }}/git_src/releases"
# cashcard consumer 
# cashcard consumer build

applications:
  - name: "db"
    repo: "db-build"
    artifact: "sportsbet-db-release-compiled"
    directory: "sportsbet-release-sources"
    version: "latest"
    static: "N"
    mvn: "N"

  - name: "core"
    repo: "parent-build"
    artifact: "sportsbet-release-sources"
    directory: "sportsbet-release-sources"
    version: "latest"
    static: "Y"
    mvn: "Y"

  - name: "obmw"
    repo: "obmw-build"
    artifact: "sportsbet-obmw-release-sources"
    directory: "sportsbet-release-sources/obmw"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "stl_engine"
    repo: "settlement-engine-build"
    artifact: "sportsbet-stl-engine-release-sources"
    directory: "sportsbet-stl-engine-release-sources"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "oxiapi"
    repo: "oxi-api-build"
    artifact: "sportsbet-oxi-api-release-sources"
    directory: "sportsbet-oxi-api-release-source"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "AF"
    repo: "activity-feeds-build"
    artifact: "sportsbet-activity-feeds-release-sources"
    directory: "sportsbet-activity-feeds-release-sources"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "livepublish"
    repo: "livepublish-build"
    artifact: "sportsbet-livepublish-release-sources"
    directory: "sportsbet-livepublish-release-sources"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "ntt_audit_java"
    repo: "ntt-audit-java-build"
    artifact: "sportsbet-ntt-audit-java-release-sources"
    directory: "sportsbet-ntt-audit-java-release-sources"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "HUC"
    repo: "hier-upd-consumer-build"
    artifact: "sportsbet-hier-upd-consumer-release-sources"
    directory: "hierarchy-update-consumer-release/sources"
    version: "latest"
    static: "N"
    mvn: "Y"

  # Double check the below apps list to make sure paths are correct
  - name: "parent_build"
    repo: "parent-build"
    artifact: "sportsbet-parent-build-release-sources"
    directory: "sportsbet-parent-build-release-sources"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "oxiapi_build"
    repo: "oxi-api-build"
    artifact: "sportsbet-oxi-api-build-release-sources"
    directory: "sportsbet-oxi-api-build-release-source"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "obmw_build"
    repo: "obmw-build"
    artifact: "sportsbet-obmw-build-release-sources"
    directory: "sportsbet-release-sources/obmw-build"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "AF_build"
    repo: "activity-feeds-build"
    artifact: "sportsbet-activity-feeds-build-release-sources"
    directory: "sportsbet-activity-feeds-build-release-sources"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "settlement_engine_build"
    repo: "settlement-engine-build"
    artifact: "sportsbet-settlement-engine-build-release-sources"
    directory: "sportsbet-settlement-engine-build-release-sources"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "livepublish_build"
    repo: "livepublish-build"
    artifact: "sportsbet-livepublish-build-release-sources"
    directory: "sportsbet-livepublish-build-release-sources"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "ntt_audit_java_build"
    repo: "ntt-audit-java-build"
    artifact: "sportsbet-ntt-audit-java-build-release-sources"
    directory: "sportsbet-ntt-audit-java-build-release-sources"
    version: "latest"
    static: "N"
    mvn: "Y"

  - name: "HUC_build"
    repo: "hier-upd-consumer-build"
    artifact: "sportsbet-hier-upd-consumer-build-release-sources"
    directory: "hierarchy-update-consumer-build-release/sources"
    version: "latest"
    static: "N"
    mvn: "Y"
