---
target: local

# Local machine IP
machine_ip: 10.211.55.4

# Region & VPC
ec2_region: eu-west-2
subnet: subnet-3018257a
vpc_id: vpc-92a750fb

# Project specific parameters
project_label: "stack-provisioner"
project_name: "Stack Provisioner"
project_dirs:
  src: "{{ playbook_dir }}/../docs/sample/app.sample/"
  dest: /opt/app

# Instance parameters
# NOT REQUIRED FOR LOCAL MACHINE

# Launch commands, before attempting to install anything else; good opportunity to install configure AMI-specific items
commands:
  - apt-get update && apt-get -y install python

# Update the following URL based on the RHEL/RedHat linux distro being used.
ee:
  enabled: false
  url: ""
  version: 7

# Security group rules
# NOT REQUIRED FOR LOCAL MACHINE