---
target: local

# Local machine IP
instance:
  machine_ip: 10.10.0.135
  username: purinda
  ssh_key: ~/.ssh/id_rsa

# Project specific parameters
project_label: "stack-provisioner"
project_name: "Stack Provisioner"
project_dirs:
  src: "{{ playbook_dir }}/../docs/sample/app.sample/"
  dest: /opt/app

# Launch commands, before attempting to install anything else; good opportunity to install configure AMI-specific items
commands:
  - apt-get update && apt-get -y install python3

# Update the following URL based on the RHEL/RedHat linux distro being used.
ee:
  enabled: false
  url: ""
  version: 7